--- 
$:
  snyk:
    token: 'process.env.SNYK_API_TOKEN'
    reporters:
      text: ~
  preprocess:
    '$.codeclimate.token': 'eval'
    '$.snyk.token': 'eval'
    '$.snyk.reporters.github.0.token': 'eval'
  codeclimate:
    token: 'process.env.CODECLIMATE_REPO_TOKEN'
  e2e:
    pattern:                                                                # Files to include
      - /.+\.e2e\.js$/i
    ignore: ~                                                               # Files to exclude
    reporter: ~                                                             # TestCafe framework reporter
    wait:
      timeout: 5000                                                        # Timeout to wait for uri's available
      uri:                                                                  # uri's to wait before start running test cases
        - http://devexpress.github.io/testcafe/example/
        - https://www-dev.adtechmedia.io/api/
  npm:
    scripts: []                                                             # Scripts to run after installing dependencies
    dependencies:                                                           # Dependencies to add/overwrite
      chai: 'latest'
  emit:
    pattern:                                                                # Files to include
      - /.+\.js$/i
    ignore:                                                                 # Files to exclude
      - /^(.*\/)?node_modules(\/?$)?/i
  test:
    mocha:
      options:                                                              # Mocha options
        ui: 'bdd'
        reporter: 'spec'
    pattern:                                                                # Files to include
      - /.+\.spec\.js$/i
    ignore: ~                                                               # Files to exclude
  coverage:
    pattern:                                                                # Files to include
      - /.+\.js$/i
    ignore:                                                                 # Files to exclude
      - /.+\.e2e\.js$/i
      - /.+\.spec\.js$/i
      - /^(.*\/)?node_modules(\/?$)?/i
    reporters:                                                              # Istanbul reporters
      text-summary: ~
main:                                                                       # Main module definition
  root: '.'                                                                 # Root package directory (containing package.json and tests)
  dependencies: ~                                                           # Dependencies to add/overwrite (over $.npm.dependencies config)
### Add other modules here...
