language: node_js
git: {depth: 0}
node_js: [6, 7]
cache:
  bundler: true
  directories: [node_modules, $(npm root -g), $(npm config get prefix)/bin]
branches:
  only: [master, dev, stage, test]
before_install: [npm install -g run-jst --only=production]
script: run-jst run unit
