language: node_js
git:
  depth: 1
cache:
  bundler: true
  directories:
    - node_modules
    - "$(npm root -g)"
    - "$(npm config get prefix)/bin"
branches:
  only:
    - master
    - dev
    - stage
    - test
before_install:
  - "npm install -g run-jst"
script: "cd example && $SCRIPT"
matrix:
  include:
    - node_js:
        - 6 # Current LTS
        - 8 # Next LTS (@see https://nodejs.org/en/blog/release/v8.0.0/#long-term-support)
      env: SCRIPT="jst run unit"
    - node_js: 8
      env: SCRIPT="jst run e2e"
      addons:
        apt:
          packages:
            - xvfb
      install:
        - "export DISPLAY=':99.0'"
        - "Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &"