language: node_js
git:
  depth: 1
branches:
  only:
    - master
    - dev
    - stage
    - test
before_install:
  - 'ln -s $(pwd)/bin/cli.js $(npm bin -g)/recink || echo "Already linked. Skipping..."'
matrix:
  include:
    -
      node_js: 6
      script: 'recink run unit'
    -
      node_js: 8
      script: 'recink run unit'
    -
      node_js: 8
      script: 'recink run e2e'
      addons:
        apt:
          packages:
            - xvfb
      install:
        - 'export DISPLAY='':99.0'''
        - 'Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &'
