language: node_js
node_js: 8
git:
  depth: 1
cache:
  bundler: true
  directories:
    - node_modules
    - '$(npm root -g)'
    - '$(npm config get prefix)/bin'
branches:
  only:
    - master
    - dev
    - stage
    - test
script: 'cd example && $SCRIPT'
before_install:
  - 'npm install -g recink'
  - 'npm install -g recink-codeclimate'
  - 'npm install -g recink-snyk'
matrix:
  include:
    -
      env: 'SCRIPT="recink run unit -c recink-codeclimate -c recink-snyk"'
    -
      env: 'SCRIPT="recink run e2e"'
      addons:
        apt:
          packages:
            - xvfb
      install:
        - 'export DISPLAY='':99.0'''
        - 'Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &'
env:
  global:
    -
      secure: XfiTtzUGNSbkNbDHUdaw+jenmpOS3pKrTLzYYSLTcAoQWgXi1Du6UJl7LKrA9wAYB7vdMymaXbEEN7q2vygm51+Rx5NfPwVSzSFJSsa/OA4FJjR3EW4vx51z8LCf0sBOc6yTh4xPobtwqXfuCHSizzzoALrdz/ftfwLgbMgqF5uca1QLDjiVFSuJtxl1IamPa0uFL2iJqhdtt1Ip71lk6VgHkzhD73W2RXIDZJ9kq+SusF85V2+ki2wQHPpTgOwMDqAnaYob9+/r5o158J0b6bZwWWQVKAXyrO7kcfZhPyV0+W/eNof8zFPQlsSiBB0kyg2qpgL0z4mN1+L4SajbxvxnmeWtAAGsidmXywJSLqPh7j7vLefoWMWikt33VVhkA+VdvIfhd6OIbQikC+yKdkBqju3nyDdQ1PvXzs32l2JpDxEUt4Gu/i/L2DFkdXcBEoKBewCdzYvwEnL8V3NZrHsW0RZg+bYuhck6WCnNwqLIAOBcu5DzdZWIFeguLhoX5jczvd/JYMccl103jgEY3we7oLrACo4XVi4nAnR3wFbTHBKwVebmzI33AnWBHD+NXgcbC8FeoOCcZ5/MGl3/IrO9qHbaa2Ju/Z8GBEJfO2Rolp3w01mNSVznSW4bx8uq1b1nXmo2tXfcoRlzJWQ7BIAswJRzFZK2QHYq7fii9Wg=
    -
      secure: iIzuz0fRt6eHMTkAEgaXoVfin8PJIFSoa1SAvqq0uk2/3VJ8kZRVtX1+B6DVzqG1Y0ya8YhxGyamCj+QhppsV1AG6/FPXl/0grd0G7BKjjWUtWtXZhFxLa21jqwgmIGHnnUnrK7e2kVy6S0g1N61plb18dTHzzf3e2BBXtK7kqrQ1SOcu8Ywx0ljcSblGcH88b7RPCv1rzHX6XnHpCGiDvS6dGVFZMMiP+Z9OPtMidErMRJ2JRrFRBVfY5EmbCYNjPgXWRUn4KDODNw7C3dgAEFLIS/B9oJwsWiPla8urR8SofnoSeF2gCB4uasDMiHWcebMAUMCpX3IbzyZ3uhueZWMAqoe4LQIUG2TGKxK6Kfy6Epvs29XF1FU7+vNYrPIna7rTJ6X0VGtDKaMh1JTeY+PQmMP6TyJ87dJ9nZ/Pi7pzheihzd+wSPEj2oEZXi09kP/qG/vZHaS8fxbL5fAIEM8HYOElsdFGwy5/D9ktLPC2yAFyXy2p/oG8UP2W+O4sbGrlmhM+N8owc7xmsnqYpit8JnxSLj9ToEIYtqaPY8sV82qt1Fao/8yloJC+l1CaecIZeS/2KdpzGENTCDW4lM9rY9yBA3OziOKc9EX6zxVyKaWQ4qdEpY3255sRzwUnMiw+4ABP09ChX1r/t6XlwCH2rd0vJSElxXOZL4efzI=
