language: node_js
git:
  depth: 1
node_js:
  - 6 # Current LTS
  - 8 # Next LTS (@see https://nodejs.org/en/blog/release/v8.0.0/#long-term-support)
cache:
  bundler: true
  directories:
    - node_modules
    - "$(npm root -g)"
    - "$(npm config get prefix)/bin"
branches:
  only:
    - master
    - dev
    - stage
    - test
before_install:
  - "npm install -g run-jst"
script: jst run unit 