--- 
$:
  pagespeed:
    uri:                              # URIs to analyze
      - https://www-test.adtechmedia.io
    # reporters:                      # Customize Reporters (available: text, summary)
    #   summary: ~
    #   text: 
    #     - minimal: true             # Skip showing detailed statistics
    # strategy: desktop               # Available: desktop, mobile
    # filter-third-party: true        # Filter 3'rd party assets
    # locale: en                      # @see https://developers.google.com/speed/docs/insights/languagesx
