--- 
$:
  pagespeed:
    uri:                              # URIs to analyze
      - https://www.example.com
    # strategy: desktop               # Available: desktop, mobile
    # filter-third-party: true        # Filter 3'rd party assets
    # locale: en                      # @see https://developers.google.com/speed/docs/insights/languagesx
